### ISSUE TITLE
Type error on dotnet core 2.2 preview 2: missing IIdentityServerBuilder

### ISSUE THREAD

**Issue by kooshan** [AliBazzi/IdentityServer4.Contrib.RedisStore#12]
Hi,
I encountered this [issue](https://github.com/IdentityServer/IdentityServer4/issues/2624) a while ago and I finally narrowed it down to this package reference

```
<PackageReference Include="IdentityServer4.Contrib.RedisStore" Version="1.4.5" />
```
If I comment that out and dismiss the redis cache API calls everything builds flawlessly.

**Comment by AliBazzi** [comment]
I haven't tested out to adopt the library using any previews of .net core 2.2
I will try to play around with it when I have time.

But if you are keen to use the library using the preview of .net core 2.2, you can help me out by trying to pin point the issue, this library is compatible with [.net standard 1.6](https://github.com/AliBazzi/IdentityServer4.Contrib.RedisStore/blob/master/IdentityServer4.Contrib.RedisStore/IdentityServer4.Contrib.RedisStore.csproj#L4) 
And a list of [dependencies](https://github.com/AliBazzi/IdentityServer4.Contrib.RedisStore/blob/master/IdentityServer4.Contrib.RedisStore/IdentityServer4.Contrib.RedisStore.csproj#L31)
Not sure if one of them is no longer compatible with .net standard 2.1 or .net core 2.2.

**Comment by kooshan** [comment]
Thanks for the quick answer. According to the dependencies I don't see anything causing this issue except the referenced IdentityServer4 version

```
<PackageReference Include="IdentityServer4" Version="1.0.0" />
```
Would increasing that to a later version like 2.2.0 break anything?
Actually that would mandate an elevation to .netstandard2.0 and Newtonsoft.Json version >= '11.0.2'.

**Comment by AliBazzi** [comment]
I'm willing to upgrade the library targeted .net standard to 2 once Identity Server 4 v 2.3 is released.

One of the things looking forward to is to start relying on StackExchange.Redis v 2, which introduces pipelining, which requires .net standard 2 at least.

but for the time being, I will keep the current release of the library compatible with Identity server 4 v 1.0.0 for all the customers who are still relying on that and not willing to upgrade.

**Comment by kooshan** [comment]
Fine! thanks. I guess I have to go with commenting out the caching and wait.

**Comment by AliBazzi** [comment]
Hi @kooshan 
I may found the cause of the error, because Identity Server 4 team [introduced](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4.csproj#L32) this new library : [IdentityServer4.Storage](https://github.com/IdentityServer/IdentityServer4.Storage)
Which is a breaking change, the current implementation of IdentityServer4.Contrib.RedisStore
 will not work because the interfaces the library relies on are not in `IdentityServer4` nuget package anymore, I need to work on that soon.

**Comment by AliBazzi** [comment]
@kooshan 
Please do verify that this [preview release](https://www.nuget.org/packages/IdentityServer4.Contrib.RedisStore/2.0.0-preview1) solves your problem

**Comment by Hub24Amir** [comment]
I have the same issue with dotnet core 2.0 and dentityServer4.Contrib.RedisStore 2.0.0  :(

**Comment by Hub24Amir** [comment]
Thanks for quick response. i guess situation is similar to what Kooshan mentioned however i just want to add using ver 2.0 didnt solve the issue. previously you asked Kooshan if ver 2 preview release does solve the issue. Thanks

**Comment by AliBazzi** [comment]
Can you share more about your current setup, nuget packages version .. etc
