### ISSUE TITLE
Unable to access grants after using redis operational store

### ISSUE THREAD

**Issue by sai-nagarjuna-t** [AliBazzi/IdentityServer4.Contrib.RedisStore#16]
I have configured my clients, resources and identity resources to be in-memory 
and I have my custom profile service implemented.
```
services.AddIdentityServer()
.AddInMemoryApiResources(Config.GetAPIResources())
.AddInMemoryClients(Config.GetClients())
.AddInMemoryIdentityResources(Config.GetIdentityResources())
.AddProfileService<ProfileService>()
```
After adding the IdentityServer4.Contrib.RedisStore for operational data, I am unable to see any of the issued grants in my grants screen 

> localhost:5000/grants

What I observe is that the GetAllAsync(string subjectId) in PersistedGrantStore.cs is called with a subjectId that is not returning any data from redis.

Please help if I am missing anything to fix this.

**Comment by AliBazzi** [comment]
Hi @sai-nagarjuna-t 
In the sample code you provided doesn't register Redis as the operational data store by doing something like:
```
...
.AddOperationalStore(options =>
    {
        options.RedisConnectionString = "---redis store connection string---";
        options.Db = 1;
    })
```

**Comment by sai-nagarjuna-t** [comment]
Hi Ali,
My bad, I have figured out to solve the prb. Sry for raising an issue.
But I have a question in general - is where a way in IDS 4 for the admin to view all the grants issued for all the users.(if it is possible)

**Comment by AliBazzi** [comment]
Hi @sai-nagarjuna-t 
This idea is against the secrecy of grants, I don't think there is a way to show that.
