### ISSUE TITLE
ConnectionMultiplexer Issue

### ISSUE THREAD

**Issue by javaadpatel** [AliBazzi/IdentityServer4.Contrib.RedisStore#18]
After updating to IdentityServer4 v2.4, I was forced to update this library to v2.0 but now I have an error about the ConnectionMultiplexer existing in both StackExchange.Redis.StrongName and StackExchange.Redis. I'm using a dotnet core 2.1 project.

Do you know how to resolve this conflict?
<img width="287" alt="ConnectionMultiplexer" src="https://user-images.githubusercontent.com/22832462/57790452-0dcfaa80-773b-11e9-91b5-19ab1d9910ae.PNG">

**Comment by AliBazzi** [comment]
Looks like `StackExchange.Redis.StrongName` package is referenced by one of the framework library that you depends on in .Net core 2.1, maybe it's `Microsoft.AspNetCore.All`, that's why there is this conflict, please check out your references or share the list here so I have more context to help.

**Comment by javaadpatel** [comment]
I checked out my references, one of them causing an issue was **Microsoft.AspNetCore.All** which I uninstalled and then installed all the individual packages. The two others were **Microsoft.Extensions.Caching.Redis** which i swopped out for **Microsoft.Extensions.Caching.StackExchangeRedis**, and then **Microsoft.AspNetCore.DataProtection.Redis** which i swopped out for **"Microsoft.AspNetCore.DataProtection.StackExchangeRedis**.

Thanks for the help and the awesome library.

**Comment by AliBazzi** [comment]
Glad it helped you out, you are welcome !
