### ISSUE TITLE
Make it possible to reuse existing multiplexer

### ISSUE THREAD

**Issue by joukevandermaas** [AliBazzi/IdentityServer4.Contrib.RedisStore#19]
Our app already has a `ConnectionMultiplexer`, and for optimal performance we should re-use it when integrating this library. However, I cannot find the option to pass in an existing `StackExchange.Redis.ConnectionMultiplexer` instance to this library.

Is this something you would be willing to add? If you are open to it, I can perhaps open a PR to add this feature.

**Comment by AliBazzi** [comment]
@joukevandermaas 
Sure, go ahead and submit a PR please, happy to add that as an option
