### ISSUE TITLE
License clarification 

### ISSUE THREAD

**Issue by jimbergstrom** [AliBazzi/IdentityServer4.Contrib.RedisStore#2]
Awesome work on this project, but It doesn't look like there's a LICENSE file in this repository and README.md doesn't mention any licence terms.

Since uncertainty around licensing can prevent some people from using or contributing to a project, I'd suggest adding a LICENSE file. 

https://choosealicense.com/ has guidence around selecting the right open-source license for your project.

**Comment by AliBazzi** [comment]
Added the MIT license for both projects (3,4), thanks for pointing that out.
