### ISSUE TITLE
Configure TTL to redis keys 

### ISSUE THREAD

**Issue by bmenezes05** [AliBazzi/IdentityServer4.Contrib.RedisStore#34]
I am using IdentityServer4 configured to use the Redis as an operational store. I would like to know if its possible to configure an expiration time for keys saved?  

This is my configuration:
`.AddOperationalStore(options =>
{
     options.RedisConnectionString = settings.RedisConnectionString;
     options.KeyPrefix = PREFIX_OPERATIONAL_STORE;
     options.Db = 0;
}`

I'm using Implicit Flow to authenticate and my keys are being saved with TTL -1.

Can you help me?

**Comment by AliBazzi** [comment]
Hi,

The library will respect the ttl for each key given by identity server 4, so you don't have to configure that manually from your side as a consumer of the library.

Can you elaborate more ?

**Comment by seygi** [comment]
@AliBazzi where can i configure the ttl for each client keys? Do you know what is the property?

Can you help us please?

**Comment by AliBazzi** [comment]
@seygi you can configure ttl of each client on Identity server side, not on the library side
you can look here: https://identityserver4.readthedocs.io/en/latest/reference/client.html

**Comment by bmenezes05** [comment]
@AliBazzi According of documentation:

> 2. for Key(SubjectId) and Key(SubjectId,ClientId) the expiration is not set, since the same and only store type is persisting the grants regardless of their type

I have a lot of users authenticating in my app and I don't want to keep their data in my storage for more than one month. Is there a way to set an expiration time in this case?

**Comment by AliBazzi** [comment]
nope, there is no way, you rely on your eviction policy configured in Redis.

**Comment by AliBazzi** [comment]
I will close this, feel free to open if you have more questions
