### ISSUE TITLE
V 3.* fails with IdentityServer4 V4

### ISSUE THREAD

**Issue by jhancock4d** [AliBazzi/IdentityServer4.Contrib.RedisStore#37]
The new version is out and this causes it all to fail...

**Comment by AliBazzi** [comment]
I will look into what's new in v4 of IdServ and update it if it's smooth update, but from your comments it doesn't look like it's straightforward.

**Comment by rangvald86** [comment]
Hi, was updating to IdentityServer4 v4.0.0 and IdentityServer4.Contrib.RedisStore 3.1.1 today. I getting this error:

An error occurred while starting the application.
TypeLoadException: Method 'GetAllAsync' in type 'IdentityServer4.Contrib.RedisStore.Stores.PersistedGrantStore' from assembly 'IdentityServer4.Contrib.RedisStore, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Microsoft.Extensions.DependencyInjection.IdentityServerRedisBuilderExtensions.AddOperationalStore(IIdentityServerBuilder builder, Action<RedisOperationalStoreOptions> optionsBuilder)

TypeLoadException: Method 'GetAllAsync' in type 'IdentityServer4.Contrib.RedisStore.Stores.PersistedGrantStore' from assembly 'IdentityServer4.Contrib.RedisStore, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Do not know if its of any help or if its even related. Would just be nice to get a solution to it :)

**Comment by AliBazzi** [comment]
V4 introduced a breaking change on the `IPersistedGrantStore`, and I've looked quickly at it (didn't have the time to look at it fully) and I'm afraid those changes to V4 will leave `RedisOperationalStore` unusable.

I will update here once I confirm my findings.

**Comment by rajeshaz09** [comment]
@AliBazzi  I don't think we can use redis as operational store going forward. V4 introduced [PersistedGrantFilter](https://github.com/IdentityServer/IdentityServer4/blob/4.0.0/src/Storage/src/Stores/PersistedGrantFilter.cs). This will be used to query data like SQL where clause. Check [InMemoryPersistedGrantStore](https://github.com/IdentityServer/IdentityServer4/blob/4.0.0/src/IdentityServer4/src/Stores/InMemory/InMemoryPersistedGrantStore.cs) for reference.

**Comment by AliBazzi** [comment]
I've released an RC for the library that include modified implementation for the V4.
#39

**Comment by AliBazzi** [comment]
changes merged, and v4 released.
