### ISSUE TITLE
can i use redis just as cache

### ISSUE THREAD

**Issue by liugt34** [AliBazzi/IdentityServer4.Contrib.RedisStore#5]
i want save the config data to mysql ,and use the redis as a cache ,how can i do it? thank u

**Comment by liugt34** [comment]
and i don't understand  what different between the method "AddConfigurationStore" and "AddConfigurationStoreCache"

**Comment by AliBazzi** [comment]
Hi @liugt34 

You would follow the following code as an example:

```csharp
            services.AddIdentityServer()
            .AddRedisCaching(options =>
            {
                options.RedisConnectionString = "--redis connection string --";
            })
            .AddClientStoreCache<IdentityServer4.EntityFramework.Stores.ClientStore>()
            .AddResourceStoreCache<IdentityServer4.EntityFramework.Stores.ResourceStore>();
```

For the second question, this method is in `IdentityServer4.EntityFramework` package, please take a look at it's implementation [here](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/aeac6f2c053571af6122e89f370f385ba01173b0/src/IdentityServer4.EntityFramework/Extensions/IdentityServerEntityFrameworkBuilderExtensions.cs#L80)

**Comment by liugt34** [comment]
@AliBazzi  thank you very much
