### ISSUE TITLE
StackExchange.Redis throw Errors

### ISSUE THREAD

**Issue by walt-liuzw** [AliBazzi/IdentityServer4.Contrib.RedisStore#76]
i using idsrv4 service with redis, under the request presure  i find some errors like that:

![image](https://user-images.githubusercontent.com/12151026/136879241-c034e09e-a28b-4819-9f85-a62c927778d8.png)

my nuget version:
IdentityServer4.Contrib.RedisStore 1.4.5

**Comment by AliBazzi** [comment]
Hi @walt-liuzw as you can see in exception details, you are timing out while connecting to Redis
