### ISSUE TITLE
Known issue with StackExchange.Redis.StrongName version 1.2.4 

### ISSUE THREAD

**Issue by RyanWChild** [AliBazzi/IdentityServer4.Contrib.RedisStore#8]
Would it be possible to update StackExchange.Redis.StrongName to version 1.2.5? There is a known issue with 1.2.4 that prevents Redis connections from being re-established after a network interruption. Link to the issue here: https://github.com/StackExchange/StackExchange.Redis/issues/559. Thank you for your time!

**Comment by AliBazzi** [comment]
Hi @RyanWChild 
AFAIK, you can install the package in your project manually to the version you desire (> 1.2.4) and this dependency version will override the version this library relies on.

Please let me know if that will help.

**Comment by RyanWChild** [comment]
Hi @AliBazzi!

I previously updated the version of StackExchange.Redis I'm using after encountering the reconnect issue in production, and it does override the dependency. However, I wanted to pass along that version 1.2.4 of StackExchange.Redis and StackExchange.Redis.StrongName have critical connection issues that were addressed in version 1.2.5 (https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes). I would suggest switching to 1.2.5 if possible, or at least leaving an open issue in case anyone else using this library runs into a similar issue. Thank you for your time!

Ryan

**Comment by AliBazzi** [comment]
I'm convinced, I will update the library to the latest version so that will bring more stability as you mentioned, thanks for the heads up !

**Comment by AliBazzi** [comment]
Updated and pushed to nuget
Thanks again @RyanWChild
