### ISSUE TITLE
AUTH password configuring

### ISSUE THREAD

**Issue by ddydeveloper** [AliBazzi/IdentityServer4.Contrib.RedisStore#9]
Good morning! Could you specify is it possible to set up an AUTH passsword if you configure this option for the redis service. 

I've tried to use ConfigurationOptions:

        .AddOperationalStore(opt =>
        {
            opt.RedisConnectionString = "localhost:6379";
            opt.ConfigurationOptions = new ConfigurationOptions {Password = "redispassword"};
        });

But anyway I got the following error: 

> It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. AuthenticationFailure on PING

It doesn't work in this way too:

        .AddOperationalStore(opt =>
        {
            opt.RedisConnectionString = "redispassword@localhost:6379";
        });

If I use the same password with redis-cli is it OK:

> redis 127.0.0.1:6379> auth redispassword
OK

**Comment by ddydeveloper** [comment]
@AliBazzi I've found the right way! You were right, it is not about the IdentityServer4.Contrib.RedisStore. All you need just set a password in connection string like this: 

> "localhost:6379,password=password"

The StackExchenge doc:

> https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by AliBazzi** [comment]
@ddydeveloper 
Great that your problem is solved !
